config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'

  resources :posts
  resources :users, only: %i[index]
  resources :categories, only: %i[index show new create edit update]

  get :search, to: 'posts#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categories_post.rb
class CategoriesPost < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categories_posts, dependent: :destroy
  has_many :posts, through: :categories_posts

  validates :name, presence: true, uniqueness: { message: I18n
    .t('category.error.messages.already_exists') }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :categories_posts, dependent: :destroy
  has_many :categories, through: :categories_posts
  validates :title, :body, presence: true

  def formated_data
    created_at.strftime('%d/%m/%Y')
  end

  def author?(current_user)
    user == current_user
  end

  def read_more?
    body.size >= 320
  end

  def initial_body
    read_more? ? body.at(0...320) : body
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout 'panel'

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    render layout: 'application'
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: t('category.new.success')
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path, notice: t('category.edit.success')
    else
      render :edit
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_user, only: %i[new create edit update destroy]
  before_action :set_post, only: %i[show edit update destroy]
  before_action :check_author, only: %i[edit update destroy]

  def index
    @posts = Post.all
    @categories = Category.all
  end

  def show; end

  def new
    @post = Post.new
    @categories = Category.all
    render layout: 'panel'
  end

  def create
    @post = current_user.posts.new(post_params)
    @category = Category.where(id: params[:category_ids])
    add_category(@post, @category)
    if @post.save
      redirect_to @post, notice: t('post.new.success')
    else
      render :new, layout: 'panel'
    end
  end

  def edit
    @categories = Category.all
    render layout: 'panel'
  end

  def update
    @category = Category.where(id: params[:category_ids])
    add_category(@post, @category)
    if @post.update(post_params)
      redirect_to @post, notice: t('post.edit.success')
    else
      render :edit, layout: 'panel'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def search
    @param = params[:search]
    @posts = Post.where('title like ?', "%#{@param}%")
  end

  private

  def add_category(post, categories)
    return unless categories.none? && categories.nil?

    categories.each do |category|
      post.categories << category
    end
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :user_id, category_ids: [])
  end

  def check_user
    redirect_to root_path unless user_signed_in?
  end

  def check_author
    redirect_to root_path unless @post.author?(current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'panel'
  before_action :check_user

  def index
    @posts = Post.where('user_id = ?', current_user.id)
  end

  private

  def check_user
    redirect_to root_path unless user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<br>
<% @category.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>

<%= form_with model: category, local: true do |f| %>
<fieldset>
 <div class="ls-label col-md-8">
  <%= f.label :name, class: "ls-label-text" %>
  <%= f.text_field :name, class: 'form-control col-md-10' %>
</div>
  <div class="ls-actions-btn">
  <%= f.submit botao, class: 'ls-btn ls-btn-lg' %>
</div>
<% end %>

app/views/categories/_post.html.erb
<br>
<br>
<div class="card" style="width: 40rem;">
    <% if user_signed_in? && post.author?(current_user) %>
    <div class="card-header">
      <p style="margin-left: 470px; text-decoration: none;"><%= link_to 'Editar', edit_post_path(post) %>
      <i class="fas fa-edit"></i>
      <%= link_to 'Apagar', post_path(post), method: :delete,
              data: { confirm: 'Tem certeza?' } %>
      <i class="fas fa-times-circle"></i></p>
      </div>
    <% end %>
  <div class="card-body">
    <h4 class="card-title"><b><%= link_to post.title, post %></b></h4>
    <br>
    <h6 class="card-subtitle mb-2 text-muted">Por: <strong><%=post.user.email%></strong>, em <%= post.formated_data %></h6>
    <br>
    <% if post.read_more? %>
    <pre>
      <p class="card-text" style="font-size: 16px;"><%= post.initial_body %>...</p>
    </pre>
      <p style="font-size: 18px; color: #000;"><%= link_to 'Ler mais', post_path(post) %></p>
    <% else %>
      <pre>
        <p class="card-text" style="font-size: 16px;"><%= post.body %></p>
      </pre>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<br>
<h1>Editar Categoria</h1>
<br>

<%= render partial: 'form', locals: { category: @category, botao: t('category.edit.submit') } %>

app/views/categories/index.html.erb
<br>
<div class="ls-box">
  <% if @categories.any? %>
  <h4>Categorias</h4>
    <table class="ls-table">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Infos</th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.name %></td>
            <td><%= link_to 'Editar', edit_category_path(category), class: 'ls-btn' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
  <p>Você não possui categorias</p>
  <% end %>
</div>

app/views/categories/new.html.erb
<br>
<h1>Nova Categoria</h1>
<br>

<%= render partial: 'form', locals: { category: @category, botao: t('category.new.submit') } %>

app/views/categories/show.html.erb
<br>
<h3><strong><%= @category.name %></h3></strong>
<br>
<% if @category.posts.any? %>
  <% @category.posts.each do |post| %>
    <%= render partial: 'post', locals: { post: post } %>
  <% end %>
<% else %>
  <h3>Não há postagens nessa categoria</h3>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GuriDev</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
  integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
  crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="main">
      <%= notice %>
      <%= alert %>
      <!-- flashes goes here -->
      <div class="container">
        <%= yield %>
      </div>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/panel.html.erb
<!DOCTYPE html>
<html class="ls-theme-orange">
  <head>
    <title>Painel do Usuário - GuriDev</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <div class="ls-topbar ">

    <!-- Barra de Notificações -->
    <div class="ls-notification-topbar">
      <!-- Links de apoio -->
      <!-- <div class="ls-alerts-list">
        <a href="#" class="ls-ico-bell-o" data-counter="8" data-ls-module="topbarCurtain" data-target="#ls-notification-curtain"><span>Notificações</span></a>
        <a href="#" class="ls-ico-bullhorn" data-ls-module="topbarCurtain" data-target="#ls-help-curtain"><span>Ajuda</span></a>
        <a href="#" class="ls-ico-question" data-ls-module="topbarCurtain" data-target="#ls-feedback-curtain"><span>Sugestões</span></a>
      </div> -->

      <!-- Dropdown com detalhes da conta de usuário -->
      <div data-ls-module="dropdown" class="ls-dropdown ls-user-account">
        <a href="#" class="ls-ico-user">
          <span class="ls-name" >
            <% if user_signed_in? %>
              <%= "Olá, #{current_user.email}" %>
            <% end %>
          </span>
        </a>

        <nav class="ls-dropdown-nav ls-user-menu">
          <ul>
            <li><%= link_to 'Sair', destroy_user_session_path, method: 'DELETE' %></li>
           </ul>
        </nav>
      </div>
    </div>

    <span class="ls-show-sidebar ls-ico-menu"></span>
    <!-- Nome do produto/marca com sidebar -->
    <h1 class="ls-brand-name" id='header_title'>
      <a href="/users" class="ls-ico-code">
        <small><strong>Painel do Usuário</strong></small>
        GuriDev
      </a>
    </h1>

    <!-- Nome do produto/marca sem sidebar quando for o pre-painel  -->
  </div>
  <aside class="ls-sidebar">
    <div class="ls-sidebar-inner">
        <nav class="ls-menu" id='side_menu'>
          <ul>
            <li><%= link_to 'Ver Blog', root_path, class: 'ls-submenu-item ls-ico-code' %></li>
            <li><%= link_to 'Nova Postagem', new_post_path, class: 'ls-submenu-item ls-ico-plus' %></li>
            <li><%= link_to 'Nova Categoria', new_category_path, class: 'ls-submenu-item ls-ico-plus' %></li>
            <li><%= link_to 'Ver Categorias', categories_path, class: 'ls-submenu-item ls-ico-list2' %></li>
          </ul>
        </nav>
    </div>
  </aside>
  <main class="ls-main ">
    <div class="container-fluid">
      <% flash.each do |name, msg| %>
        <div class="ls-alert-<%= name %>"><%= msg %></div>
      <% end %>
      <%= yield %>
    </div>
  </main>

  <aside class="ls-notification">
    <nav class="ls-notification-list" id="ls-notification-curtain" style="left: 1716px;">
      <h3 class="ls-title-2"><%=  %></h3>
      <ul>

      </ul>
    </nav>

    <nav class="ls-notification-list" id="ls-help-curtain" style="left: 1756px;">
      <h3 class="ls-title-2"><%= %></h3>
      <ul>

      </ul>
    </nav>

    <nav class="ls-notification-list" id="ls-feedback-curtain" style="left: 1796px;">
      <h3 class="ls-title-2"><%= 'help' %></h3>
      <ul>
        <li class="ls-txt-center hidden-xs">
          <a href="#" class="ls-btn-dark ls-btn-tour"><%= 'tour' %></a>
        </li>
        <li><a href="#"><%= 'guide' %></a></li>
        <li><a href="#"><%= 'wiki' %></a></li>
      </ul>
    </nav>
  </aside>
  </body>
</html>

app/views/posts/_form.html.erb
<br>
<% @post.errors.full_messages.each do |message| %>
  <p><%= message %></p>
<% end %>

<%= form_with model: post, local: true do |f| %>
<fieldset>
 <div class="ls-label col-md-8">
  <%= f.label :title, class: "ls-label-text" %>
  <%= f.text_field :title, class: 'form-control col-md-10' %>
</div>
<div class="ls-label col-md-8">
  <%= f.label :body, class: "ls-label-text" %>
  <%= f.text_area :body, rows: "20", class: "ls-textarea-autoresize" %>
</div>
<div class="ls-label col-md-6">
  <% if !categories.nil? %>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |b| %>
   <div class="form-check-inline">
     <%= b.check_box %>
     <%= b.label %>
   </div>
 <% end %>
  <% end %>
</div>
  <div class="ls-actions-btn">
  <%= f.submit botao, class: 'ls-btn ls-btn-lg' %>
</div>
<% end %>

app/views/posts/_initial_post.html.erb
<br>
<br>
<div class="card" style="width: 40rem;">
    <% if user_signed_in? && post.author?(current_user) %>
    <div class="card-header">
      <p style="margin-left: 470px; text-decoration: none;"><%= link_to 'Editar', edit_post_path(post) %>
      <i class="fas fa-edit"></i>
      <%= link_to 'Apagar', post_path(post), method: :delete,
              data: { confirm: 'Tem certeza?' } %>
      <i class="fas fa-times-circle"></i></p>
      </div>
    <% end %>
  <div class="card-body">
    <h4 class="card-title"><b><%= post.title %></b></h4>
    <br>
    <h6 class="card-subtitle mb-2 text-muted">Data: <%= post.formated_data %></h6>
    <br>
    <% if post.read_more? %>
    <pre>
      <p class="card-text" style="font-size: 16px;"><%= post.initial_body %>...</p>
    </pre>
      <p style="font-size: 18px; color: #000;"><%= link_to 'Ler mais', post_path(post) %></p>
    <% else %>
      <pre>
        <p class="card-text" style="font-size: 16px;"><%= post.body %></p>
      </pre>
    <% end %>
    <br>
    <p>Por: <%= post.user.email %></p>
  </div>
</div>

app/views/posts/_post.html.erb
<br>
<br>
<div class="card" style="width: 40rem;">
    <% if user_signed_in? && post.author?(current_user) %>
    <div class="card-header">
      <p style="margin-left: 470px; text-decoration: none;"><%= link_to 'Editar', edit_post_path(post) %>
      <i class="fas fa-edit"></i>
      <%= link_to 'Apagar', post_path(post), method: :delete,
              data: { confirm: 'Tem certeza?' } %>
      <i class="fas fa-times-circle"></i></p>
      </div>
    <% end %>
  <div class="card-body">
    <h4 class="card-title"><b><%= post.title %></b></h4>
    <br>
    <h6 class="card-subtitle mb-2 text-muted">Data: <%= post.formated_data %></h6>
    <br>
    <pre>
      <p class="card-text" style="font-size: 16px;"><%= post.body %></p>
    </pre>
    <br>
    <p>Por: <%= post.user.email %></p>
    <strong><p>Categorias:</strong>
      <% if post.categories.any? %>
      <div class="row no-gutter">
        <% post.categories.each do |category| %>
          <p class="card inline" style="width: 7rem; padding: 5px; text-align: center">
            <%= category.name %></p>
        <% end %>
      </div>
      <% else %>
        <p>Nenhuma categoria selecionada</p>
      <% end %>
    </p>
  </div>
</div>

app/views/posts/edit.html.erb
<br>
<h1>Editar Postagem</h1>
<br>

<%= render partial: 'form', locals: { post: @post, categories: @categories,
                                      botao: t('post.edit.submit') } %>

app/views/posts/index.html.erb
<br>
<h1>Blog do Erick</h1>
<br>
<% if @posts.any? %>
  <% @posts.each do |post| %>
    <%= render partial: 'initial_post', locals: { post: post } %>
  <% end %>
<% else %>
  <h3>Ainda não há postagens!</h3>
<% end %>

app/views/posts/new.html.erb
<br>
<h1>Nova Postagem</h1>
<br>

<%= render partial: 'form', locals: { post: @post, categories: @categories,
                                      botao: t('post.new.submit') } %>

app/views/posts/search.html.erb
<br>
<% if @posts.any? %>
  <h3><%= @posts.length %> resultado(s) encontrado(s)!</h3>
  <br>
  <ul>
    <% @posts.each do |post| %>
      <li><%= link_to post.title, post %></li>
      <br>
    <% end %>
  <ul>
<% else %>
  <h3>Nenhum resultado encontrado :(</h3>
<% end %>

app/views/posts/show.html.erb
<%= render partial: 'post', locals: { post: @post } %>

app/views/shared/_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
    <a href="#top" style="color: #000;">Topo</a>
    </p>
    <p style="color: #000;">GuriDev ©</p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" id="top">
  <%= link_to 'GURI', root_path, class: 'navbar-brand' %><i class="fab fa-dev dev-size"></i>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Categorias
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% @categories = Category.all %>
              <% if @categories.any? %>
                <% @categories.each do |category| %>
                  <%= link_to category.name, category, class: 'dropdown-item' %>
                <% end %>
              <% else %>
              <a class="dropdown-item" href="#">Não há categorias</a>
              <% end %>
            </div>
      </li>
      <li class="nav-item active">
        <a class="nav-link">Autor</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link">Contato</a>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Painel do Usuário', users_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <a class="nav-link"><%= current_user.email %></a>
      </li>
      <% end %>
    </ul>
    <i class="fas fa-search" style="margin-left:10px;"></i>
    <div class="navbar-form navbar-right" role="search" style="position: relative;">
      <%= form_with url: search_path, method: :get, class: 'form-inline',
                    local: true do |f| %>
        <%= f.label :search, 'Busca', class: 'sr-only' %>
        <%= f.text_field :search, class: 'form-control mx-sm-2' %>
        <%= f.submit 'Buscar', class: 'btn btn-outline-dark my-2 my-sm-0' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/users/index.html.erb
<h1 class="ls-title-intro ls-ico-home">Bem Vindo, <%= current_user.email %></h1>

<div class="ls-box">
  <% if @posts.any? %>
  <h4>Suas postagens</h4>
    <table class="ls-table">
      <thead>
        <tr>
          <th>Título</th>
          <th>Data</th>
          <th class="hidden-xs">Info</th>
        </tr>
      </thead>
      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= post.title %></td>
            <td><%= post.formated_data %></td>
            <td><%= link_to 'Detalhes', post, class: 'ls-btn' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
  <p>Você não possui postagens</p>
  <% end %>
</div>